#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Angel Rose Jeemon | Reg No: 24BAS10012
# Course: Open Source Software
# Description: Asks the user three questions interactively and generates
#              a personalised open source philosophy statement saved to a file.
# Note on aliases: alias today='date +%d-%B-%Y'
# Aliases are shortcuts for longer commands — a key shell productivity tool.

echo "=================================================="
echo "      Open Source Manifesto Generator             "
echo "=================================================="
echo ""
echo "  Answer three questions to generate your manifesto."
echo ""

# read: Takes interactive input from the user
# -p flag displays a prompt before waiting for input
read -p "  1. Name one open-source tool you use every day: " TOOL
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "  3. Name one thing you would build and share freely: " BUILD

# Capture the current date
DATE=$(date '+%d %B %Y')

# Define output filename personalised per user
OUTPUT="manifesto_$(whoami).txt"

# Compose the manifesto using string concatenation
# > creates the file fresh, >> appends each line
echo "==================================================" > "$OUTPUT"
echo "         MY OPEN SOURCE MANIFESTO                " >> "$OUTPUT"
echo "==================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Every day, I rely on $TOOL — a piece of software" >> "$OUTPUT"
echo "  that someone built and chose to share with the world for free." >> "$OUTPUT"
echo "  To me, freedom means $FREEDOM. That single word captures" >> "$OUTPUT"
echo "  why open source matters: the right to use, study," >> "$OUTPUT"
echo "  modify, and share the tools that shape our lives." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  I believe that knowledge grows when it is shared, not hoarded." >> "$OUTPUT"
echo "  Just as Mozilla built Firefox to free the web from a single" >> "$OUTPUT"
echo "  corporation's control, I commit to the open source spirit." >> "$OUTPUT"
echo "  One day, I hope to build $BUILD and release it freely." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Open source is not just a license. It is a philosophy." >> "$OUTPUT"
echo "  The tools of the future should belong to everyone." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "--------------------------------------------------" >> "$OUTPUT"
echo "  Generated by : $(whoami)" >> "$OUTPUT"
echo "  Date         : $DATE" >> "$OUTPUT"
echo "  Software     : Mozilla Firefox (MPL 2.0)" >> "$OUTPUT"
echo "==================================================" >> "$OUTPUT"

echo ""
echo "  Manifesto saved to: $OUTPUT"
echo "--------------------------------------------------"
echo ""
cat "$OUTPUT"
echo "=================================================="
